### ISSUE TITLE
Sen Tars not working

### ISSUE THREAD

**Issue by HighCodee** [BishopFox/unredacter#5]
As a [persona/system/team],
I want to [perform some task/action]
so that [achieve some goal/result]

## Overview
Clear details of what the minimum requirements are to complete this epic

## Acceptance Criteria
- [ ] Security implications approved
- [ ]

## Stake Holders
- [persona/team/business function]

#### Non Functional Requirements/Wants
- [ ]

**Comment by bolshoytoster** [comment]
@HighCodee could you provide more details?

How does it not work?
