### ISSUE TITLE
Works not with additional Fonts/Colors

### ISSUE THREAD

**Issue by Bizarrus** [BishopFox/unredacter#7]
The approach is good, but it has its weaknesses:
The "reverse engineering" works only with a constant font or the right font color.

However, if you use font types other than Arial and other than black (Used by Unredacter), it becomes difficult. Especially if the original font is not known.

**Comment by 0xffccdd** [comment]
I guess it's an issue of the training set - train on a new font?
And you can change the color of images...

**Comment by Bizarrus** [comment]
I think, the best solution is, to create an configuration-file to set global the colors/fonts for that.

Another training solution is, to iterate with one character-part over known fonts to determinate the right.

**Comment by dan-bishopfox** [comment]
There is no training set, this isn't a machine learning application. You just need to get the right font and change it to that.

**Comment by 5C3P73ROF** [comment]
What should I modify to change the font and background color?
